<?php
/**
 * Created by PhpStorm.
 * User: guilherme
 * Date: 26/08/2017
 * Time: 22:21
 */

class UserException extends Exception
{

    public function __construct($message = "", $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }

    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }
}